// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALlCRzGGFTh7Um0p_u6PH-LqsIOwOnhvQ',
    appId: '1:299529257771:web:85ae8cd521720e4173fb6e',
    messagingSenderId: '299529257771',
    projectId: 'igt-mobile-b55be',
    authDomain: 'igt-mobile-b55be.firebaseapp.com',
    storageBucket: 'igt-mobile-b55be.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVfHVrw1FrP0a-zCs6YakqIq_DCZ7Sd0I',
    appId: '1:299529257771:android:cafaba4d7dfae29a73fb6e',
    messagingSenderId: '299529257771',
    projectId: 'igt-mobile-b55be',
    storageBucket: 'igt-mobile-b55be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl06YS7_EdhyTn0_t56c7SiHJMUOlU4WI',
    appId: '1:299529257771:ios:40c7acb6cd8b3e7673fb6e',
    messagingSenderId: '299529257771',
    projectId: 'igt-mobile-b55be',
    storageBucket: 'igt-mobile-b55be.firebasestorage.app',
    iosBundleId: 'com.igtapp.igt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl06YS7_EdhyTn0_t56c7SiHJMUOlU4WI',
    appId: '1:299529257771:ios:40c7acb6cd8b3e7673fb6e',
    messagingSenderId: '299529257771',
    projectId: 'igt-mobile-b55be',
    storageBucket: 'igt-mobile-b55be.firebasestorage.app',
    iosBundleId: 'com.igtapp.igt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALlCRzGGFTh7Um0p_u6PH-LqsIOwOnhvQ',
    appId: '1:299529257771:web:158da9a7a8cf062973fb6e',
    messagingSenderId: '299529257771',
    projectId: 'igt-mobile-b55be',
    authDomain: 'igt-mobile-b55be.firebaseapp.com',
    storageBucket: 'igt-mobile-b55be.firebasestorage.app',
  );
}
